# Generated by Django 4.2.6 on 2023-10-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_lecturer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
