# Generated by Django 4.2.6 on 2023-10-30 16:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=1000)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('picture', models.ImageField(default='static/default.jpg', upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pres_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('qty', models.IntegerField()),
                ('dosage', models.IntegerField()),
                ('total', models.FloatField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pmsapp.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmsapp.patient')),
            ],
        ),
    ]
