# Generated by Django 4.2.6 on 2023-10-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0002_remove_prescription_dosage_remove_prescription_drug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='drugprescribed',
        ),
        migrations.AddField(
            model_name='prescription',
            name='drugprescribed',
            field=models.ManyToManyField(to='pmsapp.drugprescribed'),
        ),
    ]
