# Generated by Django 4.2.6 on 2023-10-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0004_remove_prescription_drugprescribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugprescribed',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
