# Generated by Django 4.2.6 on 2023-11-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0005_drugprescribed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
